### PR TITLE
Issue #68: Upgrade to Java 11, dependencies and plugins.

### PR DESCRIPTION
**Pull request by emafazillah**
The changes on pom.xml are;

1. Upgrade to Java 11
2. Dependencies version
3. Existing plugins version
4. Add new plugin to force required Maven version
5. Add new plugin to find latest plugin or dependency versions
6. Add new plugin to detect publicly disclosed vulnerabilities

### CODE REVIEW

**Comment by fazreil** [comment]
balik rumah nnt baru aku review tgk

**Comment by fazreil** [comment]
Kak Ema, tolong bump version to 1.3.0-SNAPSHOT.

**Comment by emafazillah** [comment]
> Kak Ema, tolong bump version to 1.3.0-SNAPSHOT.

Done

**Comment by fazreil** [comment]
LGTM

**Pull request merged**
