### PR TITLE
Added Math.axisScale

### PR DESCRIPTION
**Pull request by lurhays**
Issue#16: Producing an axis scale based on the input range and input
interval from
users.

### CODE REVIEW

**Comment by punchware** [comment]
Hi Kim, I have to reject this pull request because your master is not a latest and you commit from the parent folder. Therefore a lot of unnecessary changes , other than Math.java and Jio_utest_mathTest.java class, may be apply to the if this merge happen.

Workaround:
1. Update your master to the latest.
2. Recommit only portion you modified to your master.
3. Re-request pull request.

**Comment by fazreil** [comment]
Hi Kim,

I have 2 suggestions for you:

Firstly, I would suggest that you have gitignore implemented in your local
git repository. I am not sure how you are going to do it but you will need
to have a file named .gitignore on the root of your local repository. It
should sit besides src and pom.xml.

the following should be the content of .gitignore file:

target/
>
zipFile.zip
>
testFile*/
>
log/
>
log.txt
>

This .gitignore file will prevent git from detecting files and folders with
patterns matching above expression. It will not be tracked by git anymore.

 Secondly, I looked at your repository
https://github.com/lurhays/JIO-Library, I see all of the files
that-should-not-be-tracked is committed to your repository. Now what I see
is this:

> [fazreil@jenkins-fazreil JIO-Library]$ ls -l|awk '{print $9}'
>
> clean.launch
> compile.launch
> documentation.launch
> install.launch
> log
> log.txt
> pom.xml
> README.md
> src
> target
> testFile0
> testFile1
> zipFile.zip
>

please remove these files and directories recursively:

> log
> log.txt
> target
> testFile0
> testFile1
> zipFile.zip
>

It should look like below


> [fazreil@jenkins-fazreil JIO-Library]$ ls -l|awk '{print $9}'
>
> clean.launch
> compile.launch
> documentation.launch
> install.launch
> pom.xml
> README.md
> src
>


once done, commit the changes and push to remote.

Thank you,
Fazreil Amreen
(Build Engineer)

**Comment by fazreil** [comment]
when I look at the pull request again, it looks legit. Did you remove some of the content of the pull requests?

**Comment by fazreil** [comment]
merged Kim's math axis

**Pull request closed without merging**
